name: barcode-java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17', '20', '21' ]

    environment: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Build with Gradle
      run: ./gradlew build
      env:
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_PRIVATE_KEY  }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD  }}
        REMOTE_CACHE_URL: ${{ secrets.REMOTE_CACHE_URL }}
        REMOTE_CACHE_USER: ${{ secrets.REMOTE_CACHE_USER }}
        REMOTE_CACHE_PASS: ${{ secrets.REMOTE_CACHE_PASS }}
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs
